### ISSUE TITLE
misspelled file

### ISSUE THREAD

**Issue by geromey** [hiromi2424/ImageUploader#1]
Hello,

It seems that this file is misspelled:

ImageUploader / models / behaviors / image_uplodaer.php

and should be

ImageUploader / models / behaviors / image_uploader.php

I'll try out this plugin later.

Have a nice day,

Gerome.

**Comment by hiromi2424** [comment]
hi geromey,

I no longer develop this but I am using other style to upload images.

I will refactor what I am using and publish at this repository.

wait a moment, please.

thank you.

**Comment by geromey** [comment]
THanks a lot!
